-- ============================================================
-- "KENALI DIRIMU, KENALI GEREJAMU" — SUPABASE SCHEMA
-- Versi ini merefleksikan skema yang SUDAH dibuat di project
-- Supabase Anda. Aman dijalankan ulang (idempotent) jika perlu
-- setup di project baru.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABEL KUESIONER DIAGNOSTIK (1 baris = 1 jawaban pertanyaan)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS diagnostic_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type TEXT NOT NULL,      -- 'pemuda' atau 'senior'
  question_id INT NOT NULL,     -- 1-6
  answer_value INT NOT NULL,    -- skala 1-5
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 2. TABEL HASIL KUIS ROLE ASSESSMENT (1 baris = 1 hasil final)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type TEXT NOT NULL,      -- 'pemuda' atau 'senior'
  role_name TEXT NOT NULL,      -- MENTOR | PENDOA | PELINDUNG | INOVATOR | EKSEKUTOR | PENJANGKAU
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 3. TABEL DISKUSI KELOMPOK & LOCK CASE STUDY
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_discussions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name TEXT NOT NULL,
  case_id INT UNIQUE NOT NULL,      -- UNIQUE agar 1 case hanya bisa diambil 1 kelompok (mekanisme locking realtime)
  understanding_text TEXT,          -- refleksi "memahami perasaan & pergumulan"
  communication_text TEXT,          -- refleksi "pendekatan & komunikasi"
  commitments JSONB,                -- { "checklist": [...], "note": "..." }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 4. TABEL CONTROL TIMER PRESENTER (satu baris tunggal, id = 1)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS presenter_control (
  id INT PRIMARY KEY DEFAULT 1,
  timer_seconds INT DEFAULT 900,
  is_running BOOLEAN DEFAULT FALSE,
  timer_started_at TIMESTAMPTZ,             -- ditambahkan agar countdown akurat untuk HP yang baru join
  timer_label TEXT DEFAULT 'Waktu Diskusi Kelompok',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kalau tabel presenter_control ini sudah lebih dulu Anda buat TANPA
-- kolom timer_started_at / timer_label (versi awal), dua baris ALTER
-- di bawah ini akan menambahkannya dengan aman (tidak akan error jika
-- sudah ada):
ALTER TABLE presenter_control ADD COLUMN IF NOT EXISTS timer_started_at TIMESTAMPTZ;
ALTER TABLE presenter_control ADD COLUMN IF NOT EXISTS timer_label TEXT DEFAULT 'Waktu Diskusi Kelompok';

-- Insert row default untuk timer control
INSERT INTO presenter_control (id, timer_seconds, is_running)
VALUES (1, 900, FALSE)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- AKTIFKAN REALTIME UNTUK SEMUA TABEL
-- (aman dijalankan ulang: abaikan error "already member of publication")
-- ------------------------------------------------------------
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE diagnostic_responses;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE role_results;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE group_discussions;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE presenter_control;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY (WAJIB)
-- ------------------------------------------------------------
-- Supabase mengaktifkan RLS secara default untuk tabel yang dibuat
-- lewat SQL Editor. Tanpa policy eksplisit, SEMUA akses (termasuk
-- lewat anon key dari frontend) akan ditolak dengan error 42501
-- ("new row violates row-level security policy"). Blok di bawah ini
-- membuka akses publik (cocok untuk acara satu malam tanpa login) —
-- aman dijalankan ulang.
ALTER TABLE diagnostic_responses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read diagnostic"   ON diagnostic_responses;
DROP POLICY IF EXISTS "public insert diagnostic" ON diagnostic_responses;
DROP POLICY IF EXISTS "public delete diagnostic" ON diagnostic_responses;
CREATE POLICY "public read diagnostic"   ON diagnostic_responses FOR SELECT USING (true);
CREATE POLICY "public insert diagnostic" ON diagnostic_responses FOR INSERT WITH CHECK (true);
CREATE POLICY "public delete diagnostic" ON diagnostic_responses FOR DELETE USING (true);

ALTER TABLE role_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read role_results"   ON role_results;
DROP POLICY IF EXISTS "public insert role_results" ON role_results;
DROP POLICY IF EXISTS "public delete role_results" ON role_results;
CREATE POLICY "public read role_results"   ON role_results FOR SELECT USING (true);
CREATE POLICY "public insert role_results" ON role_results FOR INSERT WITH CHECK (true);
CREATE POLICY "public delete role_results" ON role_results FOR DELETE USING (true);

ALTER TABLE group_discussions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read group_discussions"   ON group_discussions;
DROP POLICY IF EXISTS "public insert group_discussions" ON group_discussions;
DROP POLICY IF EXISTS "public update group_discussions" ON group_discussions;
DROP POLICY IF EXISTS "public delete group_discussions" ON group_discussions;
CREATE POLICY "public read group_discussions"   ON group_discussions FOR SELECT USING (true);
CREATE POLICY "public insert group_discussions" ON group_discussions FOR INSERT WITH CHECK (true);
CREATE POLICY "public update group_discussions" ON group_discussions FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "public delete group_discussions" ON group_discussions FOR DELETE USING (true);

ALTER TABLE presenter_control ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read presenter_control"   ON presenter_control;
DROP POLICY IF EXISTS "public update presenter_control" ON presenter_control;
CREATE POLICY "public read presenter_control"   ON presenter_control FOR SELECT USING (true);
CREATE POLICY "public update presenter_control" ON presenter_control FOR UPDATE USING (true) WITH CHECK (true);

-- Policy DELETE di atas (diagnostic_responses, role_results, group_discussions) dibutuhkan
-- oleh tombol sapu "Reset Semua Data" di Presenter View (index.html), yang menghapus semua
-- baris di ketiga tabel itu dan mereset presenter_control ke kondisi awal sebelum acara baru.
