-- ============================================================
-- "KENALI DIRIMU, KENALI GEREJAMU" — SUPABASE SCHEMA
-- Versi ini merefleksikan skema yang SUDAH dibuat di project
-- Supabase Anda. Aman dijalankan ulang (idempotent) jika perlu
-- setup di project baru.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABEL KUESIONER DIAGNOSTIK (1 baris = 1 jawaban pertanyaan)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS diagnostic_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type TEXT NOT NULL,      -- 'pemuda' atau 'senior'
  question_id INT NOT NULL,     -- 1-6
  answer_value INT NOT NULL,    -- skala 1-5
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 2. TABEL HASIL KUIS ROLE ASSESSMENT (1 baris = 1 hasil final)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type TEXT NOT NULL,      -- 'pemuda' atau 'senior'
  role_name TEXT NOT NULL,      -- MENTOR | PENDOA | PELINDUNG | INOVATOR | EKSEKUTOR | PENJANGKAU
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 3. TABEL DISKUSI KELOMPOK & LOCK CASE STUDY
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_discussions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name TEXT NOT NULL,
  case_id INT UNIQUE NOT NULL,      -- UNIQUE agar 1 case hanya bisa diambil 1 kelompok (mekanisme locking realtime)
  understanding_text TEXT,          -- refleksi "memahami perasaan & pergumulan"
  communication_text TEXT,          -- refleksi "pendekatan & komunikasi"
  commitments JSONB,                -- { "checklist": [...], "note": "..." }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 4. TABEL CONTROL TIMER PRESENTER (satu baris tunggal, id = 1)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS presenter_control (
  id INT PRIMARY KEY DEFAULT 1,
  timer_seconds INT DEFAULT 900,
  is_running BOOLEAN DEFAULT FALSE,
  timer_started_at TIMESTAMPTZ,             -- ditambahkan agar countdown akurat untuk HP yang baru join
  timer_label TEXT DEFAULT 'Waktu Diskusi Kelompok',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kalau tabel presenter_control ini sudah lebih dulu Anda buat TANPA
-- kolom timer_started_at / timer_label (versi awal), dua baris ALTER
-- di bawah ini akan menambahkannya dengan aman (tidak akan error jika
-- sudah ada):
ALTER TABLE presenter_control ADD COLUMN IF NOT EXISTS timer_started_at TIMESTAMPTZ;
ALTER TABLE presenter_control ADD COLUMN IF NOT EXISTS timer_label TEXT DEFAULT 'Waktu Diskusi Kelompok';

-- Insert row default untuk timer control
INSERT INTO presenter_control (id, timer_seconds, is_running)
VALUES (1, 900, FALSE)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- AKTIFKAN REALTIME UNTUK SEMUA TABEL
-- (aman dijalankan ulang: abaikan error "already member of publication")
-- ------------------------------------------------------------
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE diagnostic_responses;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE role_results;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE group_discussions;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE presenter_control;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- ------------------------------------------------------------
-- CATATAN KEAMANAN (opsional)
-- ------------------------------------------------------------
-- Keempat tabel di atas dibuat TANPA Row Level Security (RLS).
-- Di Supabase, tabel publik tanpa RLS tetap bisa diakses lewat
-- anon key (perilaku default), jadi aplikasi ini akan berfungsi
-- apa adanya — cocok untuk kebutuhan acara satu malam tanpa login.
--
-- Jika suatu saat ingin diperketat, aktifkan RLS + policy publik
-- eksplisit seperti ini (opsional, tidak wajib untuk acara ini):
--
-- ALTER TABLE diagnostic_responses ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "public read"   ON diagnostic_responses FOR SELECT USING (true);
-- CREATE POLICY "public insert" ON diagnostic_responses FOR INSERT WITH CHECK (true);
-- (ulangi pola yang sama untuk role_results, group_discussions, presenter_control,
--  dengan tambahan policy UPDATE untuk group_discussions & presenter_control)
